// Singleton — see sanity/deskStructure/index.js for how this is pinned to a
// single document in the desk tool, and sanity.config.js for the
// document-actions lockdown that prevents duplication/deletion.
//
// Holds every sitewide default currently hardcoded in Product.jsx / Footer.jsx:
// the shipping panel cells, TrustStrip items, stock-urgency copy templates,
// the "Mehfil Edit" / "Mehfil '26" edition & season labels, the size-guide
// link, and the fallback care/shipping copy products can inherit.
export default {
  name: 'siteSettings',
  title: 'Site Settings',
  type: 'document',
  groups: [
    { name: 'general', title: 'General', default: true },
    { name: 'homepage', title: 'Homepage' },
    { name: 'collections', title: 'Collections Page' },
    { name: 'pdp', title: 'Product Page' },
    { name: 'footer', title: 'Footer' },
  ],
  fields: [
    {
      name: 'homepageCollections',
      title: 'Homepage collections',
      type: 'array',
      group: 'homepage',
      of: [{ type: 'reference', to: [{ type: 'category' }] }],
      description:
        'The collection cards in the slider below the hero, in this order. Leave empty to fall back to every collection sorted by display order.',
    },
    {
      name: 'featuredCollection',
      title: 'Featured collection (product slider)',
      type: 'reference',
      group: 'homepage',
      to: [{ type: 'category' }],
      description:
        'Which collection stocks the horizontal product slider further down the homepage. Leave empty to show the whole catalogue.',
    },
    {
      name: 'featuredCollectionLimit',
      title: 'Max products in the slider',
      type: 'number',
      group: 'homepage',
      initialValue: 12,
      validation: (Rule) => Rule.min(2).max(24),
    },
    {
      name: 'collectionsIntro',
      title: 'Collections page intro',
      type: 'text',
      group: 'collections',
      rows: 3,
      description:
        'The italic line under the title on /collections (the "All" view). Each individual collection uses its own Description field instead — Collections → <name> → Description.',
    },
    {
      name: 'brandName',
      title: 'Brand name',
      type: 'string',
      group: 'general',
      initialValue: 'Lyallpurwears',
      validation: (Rule) => Rule.required(),
    },
    {
      name: 'tagline',
      title: 'Tagline',
      type: 'string',
      group: 'general',
    },
    {
      name: 'announcementText',
      title: 'Announcement bar text',
      type: 'string',
      group: 'general',
      description: 'e.g. "Free shipping over Rs. 5,000 · Cash on Delivery nationwide".',
    },
    {
      name: 'contactEmail',
      title: 'Contact email',
      type: 'string',
      group: 'general',
      validation: (Rule) => Rule.email(),
    },
    {
      name: 'contactPhone',
      title: 'Contact phone',
      type: 'string',
      group: 'general',
      description: 'Also used as the WhatsApp number — the Contact page links to it via wa.me.',
    },
    {
      name: 'contactAddress',
      title: 'Studio address',
      type: 'text',
      rows: 3,
      group: 'general',
      description: 'Shown on the Contact page. One line per line break.',
    },
    {
      name: 'contactAddressNote',
      title: 'Studio address note',
      type: 'string',
      group: 'general',
      description: 'The small line under the address, e.g. "Visits by appointment only".',
    },
    {
      name: 'contactHours',
      title: 'Opening hours',
      type: 'array',
      group: 'general',
      of: [{ type: 'string' }],
      description: 'One line per row, e.g. "Mon–Sat · 10am–7pm PKT". Shown on the Contact page.',
    },
    {
      name: 'socialLinks',
      title: 'Social links',
      type: 'array',
      group: 'footer',
      of: [{ type: 'socialLink' }],
    },
    {
      name: 'footerCopy',
      title: 'Footer copy',
      type: 'text',
      group: 'footer',
      rows: 3,
      description: 'e.g. the copyright / about line shown in the site footer.',
    },
    {
      name: 'freeShippingThreshold',
      title: 'Free shipping threshold (PKR)',
      type: 'number',
      group: 'pdp',
      initialValue: 5000,
      validation: (Rule) => Rule.required().min(0),
    },
    {
      name: 'shippingCells',
      title: 'Shipping panel cells',
      type: 'array',
      group: 'pdp',
      of: [{ type: 'shippingCell' }],
      description: 'The 4-cell grid on the PDP: Cash on Delivery, Free shipping, 7-Day Returns, Authentic Lawn.',
      validation: (Rule) => Rule.max(4).warning('The PDP shipping panel renders a 2x2 grid — more than 4 cells will overflow.'),
    },
    {
      name: 'trustStripItems',
      title: 'Trust strip items',
      type: 'array',
      group: 'pdp',
      of: [{ type: 'trustItem' }],
      description: 'The sitewide TrustStrip banner shown on Home, Collections and Product pages.',
    },
    {
      name: 'defaultEditionLabel',
      title: 'Default edition label',
      type: 'string',
      group: 'pdp',
      initialValue: 'Mehfil Edit',
      description: 'Used when a product has no editionLabel of its own.',
    },
    {
      name: 'seasonLabel',
      title: 'Season / edition badge suffix',
      type: 'string',
      group: 'pdp',
      initialValue: "Mehfil '26",
      description: 'Appended to the product badge, e.g. "New · Mehfil \'26".',
    },
    {
      name: 'sizeGuideUrl',
      title: 'Size guide URL',
      type: 'string',
      group: 'pdp',
      description: 'Where the "Size guide ↗" link on the PDP points to. Can be an internal path (e.g. /size-guide) or an external URL.',
    },
    {
      name: 'stockUrgencyTemplate',
      title: 'Stock urgency copy template',
      type: 'string',
      group: 'pdp',
      initialValue: 'Only {stock} pieces left',
      description: 'Use {stock} as a placeholder for the live stock count.',
    },
    {
      name: 'viewingNowTemplate',
      title: '"Viewing now" copy template',
      type: 'string',
      group: 'pdp',
      initialValue: '{count} people viewing this in the last hour',
      description: 'Use {count} as a placeholder for viewingNowCount.',
    },
    {
      name: 'viewingNowCount',
      title: '"Viewing now" count',
      type: 'number',
      group: 'pdp',
      initialValue: 14,
    },
    {
      name: 'defaultCareInstructions',
      title: 'Default care instructions',
      type: 'text',
      group: 'pdp',
      rows: 3,
      description: 'Fallback used when a product has no careInstructions of its own.',
      initialValue: 'Cold hand wash separately. Do not bleach. Iron on reverse. Dry in shade.',
    },
    {
      name: 'defaultShippingReturns',
      title: 'Default shipping & returns copy',
      type: 'text',
      group: 'pdp',
      rows: 3,
      description: 'Fallback used when a product has no shippingReturns of its own.',
      initialValue: '2–4 working days nationwide. Cash on Delivery available. 7-day easy returns on unworn pieces with original tags.',
    },
  ],
  preview: {
    prepare() {
      return { title: 'Site Settings' };
    },
  },
};
